global:
  scrape_interval: 2s
  evaluation_interval: 2s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']

  - job_name: 'eureka-server'
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ['host.docker.internal:8761']

  - job_name: 'api-gateway'
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ['host.docker.internal:8999']

  - job_name: 'auth-service'
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ['host.docker.internal:9988']

  - job_name: 'product-service'
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ['host.docker.internal:9091']

  - job_name: 'payment-service'
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ['host.docker.internal:9094']

  - job_name: 'order-service'
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ['host.docker.internal:9095']
